---
#
# Include the shared gitlab CI definitions
#
include:
  - project: 'enterprisemodules/gitlab_ci'
    file: 'gitlab-ci.yml'

mqiib01_demo_check:
  extends: .demo_check
  variables:
    server: ml-mqiib01
